#!/bin/sh
SERVICE_FILE="/etc/init.d/cloudflared"

echo "正在撤销 HTTP2 配置..."
# 把 --protocol http2 替换为空，即删除它
sed -i 's/ --protocol http2//g' "$SERVICE_FILE"

echo "正在重启 cloudflared 服务..."
rc-service cloudflared restart

echo "正在检查状态..."
sleep 3
rc-service cloudflared status
